package com.example.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing a patient and their CKD prediction data.
 * This maps to the 'predictor_patient' table in the database.
 */
@Entity
@Table(name = "predictor_patient")
public class Patient {

    /**
     * Primary key for the patient record.
     * Value is auto-generated by the database (auto-increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Age of patient
    private float age;

    // Blood pressure measurement
    private float bp;

    // Specific gravity of urine
    private float sg;

    // Albumin level
    private float al;

    // Model's prediction: true if CKD is likely, false otherwise
    private Boolean prediction;

    /**
     * Timestamp when the record was created.
     * Automatically set before persisting, not updatable afterward.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Sets the 'createdAt' timestamp to the current time
     * before the entity is persisted to the database.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public float getAge() {
        return age;
    }

    public void setAge(float age) {
        this.age = age;
    }

    public float getBp() {
        return bp;
    }

    public void setBp(float bp) {
        this.bp = bp;
    }

    public float getSg() {
        return sg;
    }

    public void setSg(float sg) {
        this.sg = sg;
    }

    public float getAl() {
        return al;
    }

    public void setAl(float al) {
        this.al = al;
    }

    public Boolean getPrediction() {
        return prediction;
    }

    public void setPrediction(Boolean prediction) {
        this.prediction = prediction;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
