# Generated by Django 5.2.3 on 2025-07-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('bp', models.FloatField()),
                ('sg', models.FloatField()),
                ('al', models.FloatField()),
                ('prediction', models.BooleanField(null=True)),
            ],
        ),
    ]
