# Generated by Django 5.2.3 on 2025-07-02 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 2, 19, 14, 8, 475162, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
